### ISSUE TITLE
RuntimeError: No symbol "RVALUE" in current context.

### ISSUE THREAD

**Issue by pjb3** [tmm1/gdb.rb#4]
I get this error when trying to use the ruby objects command.  Here's the output:

```
GNU gdb (GDB) 7.0
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/ruby-enterprise/bin/ruby...(no debugging symbols found)...done.
Attaching to program: /opt/ruby-enterprise/bin/ruby, process 4288
Reading symbols from /opt/ruby-enterprise/lib/libtcmalloc_minimal.so.0...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/libtcmalloc_minimal.so.0
Reading symbols from /lib/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libdl.so.2
Reading symbols from /lib/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/libcrypt.so.1
Reading symbols from /lib/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib/libm.so.6
Reading symbols from /lib/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib/libc.so.6
Reading symbols from /usr/lib/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libstdc++.so.6
Reading symbols from /lib/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/thread.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/thread.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/etc.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/etc.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/stringio.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/stringio.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/syck.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/syck.so
Reading symbols from /lib/libnss_compat.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libnss_compat.so.2
Reading symbols from /lib/libnsl.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/libnsl.so.1
Reading symbols from /lib/libnss_nis.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libnss_nis.so.2
Reading symbols from /lib/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libnss_files.so.2
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/fcntl.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/fcntl.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/socket.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/socket.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/unicorn-0.93.3/lib/unicorn_http.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/unicorn-0.93.3/lib/unicorn_http.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/nkf.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/nkf.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/racc/cparse.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/racc/cparse.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/tmail-1.2.3.1/ext/tmailscanner/tmail/tmailscanner.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/tmail-1.2.3.1/ext/tmailscanner/tmail/tmailscanner.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/x86_64-linux/iconv.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/x86_64-linux/iconv.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/mysql-2.7/lib/mysql.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/mysql-2.7/lib/mysql.so
Reading symbols from /usr/lib/libmysqlclient.so.15...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libmysqlclient.so.15
Reading symbols from /lib/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib/libpthread.so.0
Reading symbols from /lib/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/libz.so.1
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/faster_html_escape-1.0.0/./faster_html_escape.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/faster_html_escape-1.0.0/./faster_html_escape.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/strscan.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/strscan.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/memcached-0.17.3/lib/rlibmemcached.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/memcached-0.17.3/lib/rlibmemcached.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/openssl.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/openssl.so
Reading symbols from /lib/libssl.so.0.9.8...(no debugging symbols found)...done.
Loaded symbols for /lib/libssl.so.0.9.8
Reading symbols from /lib/libcrypto.so.0.9.8...(no debugging symbols found)...done.
Loaded symbols for /lib/libcrypto.so.0.9.8
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/digest/sha1.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/digest/sha1.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/digest.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/digest.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.3/lib/libxml_ruby.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.3/lib/libxml_ruby.so
Reading symbols from /usr/lib/libxml2.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libxml2.so.2
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/digest/md5.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/digest/md5.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/bigdecimal.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/bigdecimal.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/zlib.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/zlib.so
Reading symbols from /home/app/.ruby_inline/Inline__ca4f.so...done.
Loaded symbols for /home/app/.ruby_inline/Inline__ca4f.so
Reading symbols from /lib/libnss_dns.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libnss_dns.so.2
Reading symbols from /lib/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libresolv.so.2
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rmagick-2.9.2/lib/RMagick2.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rmagick-2.9.2/lib/RMagick2.so
Reading symbols from /usr/lib/libfreetype.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libfreetype.so.6
Reading symbols from /usr/lib/libMagickCore.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libMagickCore.so.1
Reading symbols from /usr/lib/liblcms.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/liblcms.so.1
Reading symbols from /usr/lib/libtiff.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libtiff.so.4
Reading symbols from /usr/lib/libjpeg.so.62...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libjpeg.so.62
Reading symbols from /usr/lib/libXext.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libXext.so.6
Reading symbols from /usr/lib/libSM.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libSM.so.6
Reading symbols from /usr/lib/libICE.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libICE.so.6
Reading symbols from /usr/lib/libX11.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libX11.so.6
Reading symbols from /usr/lib/libXt.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libXt.so.6
Reading symbols from /lib/libbz2.so.1.0...(no debugging symbols found)...done.
Loaded symbols for /lib/libbz2.so.1.0
Reading symbols from /usr/lib/libgomp.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libgomp.so.1
Reading symbols from /usr/lib/libltdl.so.7...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libltdl.so.7
Reading symbols from /usr/lib/libXau.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libXau.so.6
Reading symbols from /lib/libuuid.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/libuuid.so.1
Reading symbols from /usr/lib/libxcb.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libxcb.so.1
Reading symbols from /lib/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/librt.so.1
Reading symbols from /usr/lib/libXdmcp.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libXdmcp.so.6
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/json-1.1.4/ext/json/ext/parser.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/json-1.1.4/ext/json/ext/parser.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/json-1.1.4/ext/json/ext/generator.so...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/json-1.1.4/ext/json/ext/generator.so
Reading symbols from /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/enumerator.so...(no debugging symbols found)...done.
Loaded symbols for /opt/ruby-enterprise/lib/ruby/1.8/x86_64-linux/enumerator.so
0x00007fc5f73316f3 in select () from /lib/libc.so.6
(gdb) ruby objects
Traceback (most recent call last):
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 241, in invoke
    self.print_stats()
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 349, in print_stats
    for (obj, flags) in self.all_objects():
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 374, in all_objects
    p = gdb.eval("(RVALUE*) heaps[%i].slot" % i)
RuntimeError: No symbol "RVALUE" in current context.
Error occurred in Python command: No symbol "RVALUE" in current context.
(gdb) ruby objects classes
Traceback (most recent call last):
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 231, in invoke
    self.print_classes()
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 271, in print_classes
    for (obj, type) in self.live_objects():
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 382, in live_objects
    for (obj, flags) in self.all_objects():
  File "/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/gdb.rb-0.1.1/bin/../scripts/ruby-gdb.py", line 374, in all_objects
    p = gdb.eval("(RVALUE*) heaps[%i].slot" % i)
RuntimeError: No symbol "RVALUE" in current context.
Error occurred in Python command: No symbol "RVALUE" in current context.
```

**Comment by tmm1** [comment]
How did you install REE?

```
/opt/ruby-enterprise/bin/ruby...(no debugging symbols found)
```

shows that all the debugging symbols have been stripped out.

**Comment by pjb3** [comment]
Installed from ruby-enterprise_1.8.6-20090610_amd64.deb

**Comment by tmm1** [comment]
The debian package for REE unfortunately strips all its binaries. I've filed an with the maintainers, but for now you'd have to build your own REE using the installer.
