### ISSUE TITLE
Argument to arithmetic operation not a number or boolean.

### ISSUE THREAD

**Issue by thehenster** [tmm1/gdb.rb#6]
Hey,

Using ree-1.8.6-20090610 installed via rvm debugging a phusion passenger 3.0.5 instance and getting the following output running ruby trace.

(gdb) ruby trace 25
$4 = -61 '\303'
Traceback (most recent call last):
  File "/home/rails/.rvm/gems/ree-1.8.6-20090610/gems/gdb.rb-0.1.6/scripts/ruby-gdb.py", line 198, in invoke
    self.setup()
  File "/home/rails/.rvm/gems/ree-1.8.6-20090610/gems/gdb.rb-0.1.6/scripts/ruby-gdb.py", line 172, in setup
    gdb.execute(c)
RuntimeError: Argument to arithmetic operation not a number or boolean.
Error occurred in Python command: Argument to arithmetic operation not a number or boolean.

**Comment by tmm1** [comment]
use rbtrace for tracing. i'm going to remove this feature from gdb.rb as it is a huge hack.
